horoscope/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tuvi.urls', namespace='tuvi')),
]

tuvi/urls.py
from django.urls import path
from . import views

app_name = 'tuvi'

urlpatterns = [
    path('', views.input_form, name='input_form'),
]

tuvi/models.py
from django.db import models

# Create your models here.

tuvi/forms.py
from django import forms
import datetime


class InputForm(forms.Form):
    name = forms.CharField(
        label='Name',
        max_length=40,
        widget=forms.TextInput(
            attrs={
                'pattern': '[a-zA-Z0-9 ]+',
                'title': 'Only letters, numbers and whitespace are allowed.'
            }
        ),
        required=False,
    )

    GENDER_CHOICES = [('M', 'Male'), ('F', 'Female')]

    gender = forms.ChoiceField(label='Gender', choices=GENDER_CHOICES, widget=forms.RadioSelect, initial='M')
    year = forms.ChoiceField(label='Year', choices=[(str(year), str(year)) for year in range(1900, 2100)], initial=str(datetime.datetime.now().year))
    month = forms.ChoiceField(label='Month', choices=[(str(month), str(month)) for month in range(1, 13)])
    day = forms.ChoiceField(label='Day', choices=[(str(day), str(day)) for day in range(1, 32)])
    hour = forms.ChoiceField(label='Hour', choices=[(str(hour), str(hour)) for hour in range(24)])
    minute = forms.ChoiceField(label='Minute', choices=[(str(minute), str(minute)) for minute in range(60)])
    cur_year = forms.ChoiceField(label='Current year', choices=[(str(year), str(year)) for year in range(1900, 2100)], initial=str(datetime.datetime.now().year))

tuvi/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse, HttpResponseServerError, HttpResponseNotAllowed
from .forms import InputForm

from core.main import LaSoTuVi

import traceback

# Create your views here.

def input_form(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        form = InputForm()
        return render(request, 'tuvi/input_form.html', {'form': form})
    elif request.method == 'POST':
        form = InputForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            try:
                name = cleaned_data.get('name')
                if name is None or name == '':
                    name = 'Tử vi Tiến Minh'
                year = int(cleaned_data.get('year'))
                month = int(cleaned_data.get('month'))
                day = int(cleaned_data.get('day'))
                hour = int(cleaned_data.get('hour'))
                minute = int(cleaned_data.get('minute'))
                cur_year = int(cleaned_data.get('cur_year'))
                gender = cleaned_data.get('gender')
                if gender == 'M':
                    gender = 1
                else:
                    gender = -1

                horoscope = LaSoTuVi(year, month, day, hour, minute, gender=gender, cur_year=cur_year, hoten=name)
                image = horoscope.get_image()
                return render(request, 'tuvi/horoscope.html', {'image': image})
            except Exception as e:
                print(traceback.format_exc())
                return HttpResponseServerError()

        return render(request, 'tuvi/input_form.html', {'form': form})
    else:
        return HttpResponseNotAllowed()

tuvi/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/base.css" %}">
</head>
<body>
    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    {% block jscontent %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

tuvi/templates/tuvi/horoscope.html
{% extends "base.html" %}

{% block title %}
    Horoscope Result
{% endblock %}

{% block content %}
    <img src="data:image/png;base64,{{ image }}" alt="Horoscope Result">
{% endblock %}

{% block jscontent %}
{% endblock %}

tuvi/templates/tuvi/input_form.html
{% extends "base.html" %}

{% block title %}
    Horoscope Input Form
{% endblock %}

{% block content %}
    <h1 class="text-center mb-5 mt-2">Horoscope App</h1>
    <div id="input-div">
        <br>
        <form method="post" id="input-form">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit" class="btn btn-block btn-primary">
        </form>
    </div>
{% endblock %}

{% block jscontent %}
    <script>
        $(document).ready(function() {

            /* Decorate with bootstrap */
            $("#id_name").addClass("form-control");
            $("#id_name").attr("placeholder", "Name");

            /* End of decorate */


            let monthField = $("#id_month");
            let dayField = $("#id_day");
            let yearField = $("#id_year");

            function updateDayOptions() {
                let selectedMonth = parseInt(monthField.val(), 10);
                let selectedDay = parseInt(dayField.val(), 10);
                
                let daysInMonth = new Date(yearField.val(), selectedMonth, 0).getDate();

                dayField.find("option").each(function() {
                    let dayOption = $(this);
                    let dayValue = parseInt(dayOption.val(), 10);

                    if (dayValue > daysInMonth) {
                        dayOption.attr("disabled", true);
                    } else {
                        dayOption.attr("disabled", false);
                    }
                });

                if (selectedDay > daysInMonth) {
                    dayField.val("");
                }
            }

            // Bind the function to the change event
            monthField.change(updateDayOptions);
            yearField.change(updateDayOptions);

            updateDayOptions();
        });
    </script>
{% endblock %}